### About Dataset

Anonymous Ratings on jokes.

1. Ratings are real values ranging from -10.00 to +10.00 (the value "99" corresponds to "null" = "not rated").

2. One row per user

3. The first column gives the number of jokes rated by that user. The next 100 columns give the ratings for jokes 01 - 100.

### Read the dataset(jokes.csv)

Take care about the header in read_csv() as there are no column names given in the dataset. 

In [28]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [29]:
joke_data = pd.read_csv("jokes.csv")

#tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0, stop_words='english')
#tfidf_matrix = tf.fit_transform(ds['description'])

In [30]:
joke_data.head()

74  -7.82   8.79  -9.66  -8.16  -7.52  -8.5  -9.85  4.17  -8.98  ...    \
0  100   4.08  -0.29   6.36   4.37  -2.38 -9.66  -0.73 -5.34   8.88  ...     
1   49  99.00  99.00  99.00  99.00   9.03  9.27   9.03  9.27  99.00  ...     
2   48  99.00   8.35  99.00  99.00   1.80  8.16  -2.82  6.21  99.00  ...     
3   91   8.50   4.61  -4.17  -5.39   1.36  1.60   7.04  4.61  -0.44  ...     
4  100  -6.17  -3.54   0.44  -8.50  -7.09 -4.32  -8.69 -0.87  -6.65  ...     

   2.82.2  99.18  99.19  99.20  99.21  99.22  -5.63  99.23  99.24  99.25  
0    2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
1   99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
2   99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
3    5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
4   -3.54  -6.89  -0.68  -2.96  -2.18  -3.35   0.05  -9.08  -5.05  -3.45  

[5 rows x 101 columns]

### Print the top 5 rows

In [31]:
joke_data.head(5)

74  -7.82   8.79  -9.66  -8.16  -7.52  -8.5  -9.85  4.17  -8.98  ...    \
0  100   4.08  -0.29   6.36   4.37  -2.38 -9.66  -0.73 -5.34   8.88  ...     
1   49  99.00  99.00  99.00  99.00   9.03  9.27   9.03  9.27  99.00  ...     
2   48  99.00   8.35  99.00  99.00   1.80  8.16  -2.82  6.21  99.00  ...     
3   91   8.50   4.61  -4.17  -5.39   1.36  1.60   7.04  4.61  -0.44  ...     
4  100  -6.17  -3.54   0.44  -8.50  -7.09 -4.32  -8.69 -0.87  -6.65  ...     

   2.82.2  99.18  99.19  99.20  99.21  99.22  -5.63  99.23  99.24  99.25  
0    2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
1   99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
2   99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
3    5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
4   -3.54  -6.89  -0.68  -2.96  -2.18  -3.35   0.05  -9.08  -5.05  -3.45  

[5 rows x 101 columns]

### Consider `ratings` named dataframe with only first 200 rows and all columns from 1(first column is 0) of dataset

In [32]:
ratings_jokes=joke_data.iloc[:200,1:]

In [33]:
ratings_jokes.shape

(200, 100)

In [34]:
ratings_jokes.head()

-7.82   8.79  -9.66  -8.16  -7.52  -8.5  -9.85  4.17  -8.98  -4.76  ...    \
0   4.08  -0.29   6.36   4.37  -2.38 -9.66  -0.73 -5.34   8.88   9.22  ...     
1  99.00  99.00  99.00  99.00   9.03  9.27   9.03  9.27  99.00  99.00  ...     
2  99.00   8.35  99.00  99.00   1.80  8.16  -2.82  6.21  99.00   1.84  ...     
3   8.50   4.61  -4.17  -5.39   1.36  1.60   7.04  4.61  -0.44   5.73  ...     
4  -6.17  -3.54   0.44  -8.50  -7.09 -4.32  -8.69 -0.87  -6.65  -1.80  ...     

   2.82.2  99.18  99.19  99.20  99.21  99.22  -5.63  99.23  99.24  99.25  
0    2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
1   99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
2   99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
3    5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
4   -3.54  -6.89  -0.68  -2.96  -2.18  -3.35   0.05  -9.08  -5.05  -3.45  

[5 rows x 100 columns]

##### Change the column indices from 0 to 99

In [35]:
ratings_jokes.columns = range(ratings_jokes.shape[1])

In [36]:
ratings_jokes.head()

0      1      2      3     4     5     6     7      8      9   ...    \
0   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88   9.22  ...     
1  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  99.00  ...     
2  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00   1.84  ...     
3   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44   5.73  ...     
4  -6.17  -3.54   0.44  -8.50 -7.09 -4.32 -8.69 -0.87  -6.65  -1.80  ...     

      90     91     92    93     94     95     96     97     98     99  
0   2.82  -4.95  -0.29  7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
1  99.00  99.00  99.00  9.08  99.00  99.00  99.00  99.00  99.00  99.00  
2  99.00  99.00  99.00  0.53  99.00  99.00  99.00  99.00  99.00  99.00  
3   5.19   5.58   4.27  5.19   5.73   1.55   3.11   6.55   1.80   1.60  
4  -3.54  -6.89  -0.68 -2.96  -2.18  -3.35   0.05  -9.08  -5.05  -3.45  

[5 rows x 100 columns]

### In the dataset, the null ratings are given as 99.00, so replace all 99.00s with 0
Hint: You can use `ratings.replace(<the given value>, <new value you wanted to change with>)`

In [37]:
ratings_jokes.replace(to_replace=99.00, value=0, inplace=True)

#### Expected Output

In [38]:
ratings_jokes

0     1     2     3     4     5     6     7     8     9   ...     90  \
0    4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...   2.82   
1    0.00  0.00  0.00  0.00  9.03  9.27  9.03  9.27  0.00  0.00  ...   0.00   
2    0.00  8.35  0.00  0.00  1.80  8.16 -2.82  6.21  0.00  1.84  ...   0.00   
3    8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...   5.19   
4   -6.17 -3.54  0.44 -8.50 -7.09 -4.32 -8.69 -0.87 -6.65 -1.80  ...  -3.54   
5    0.00  0.00  0.00  0.00  8.59 -9.85  7.72  8.79  0.00  0.00  ...   0.00   
6    6.84  3.16  9.17 -6.21 -8.16 -1.70  9.27  1.41 -5.19 -4.42  ...   7.23   
7   -3.79 -3.54 -9.42 -6.89 -8.74 -0.29 -5.29 -8.93 -7.86 -1.60  ...   4.37   
8    3.01  5.15  5.15  3.01  6.41  5.15  8.93  2.52  3.01  8.16  ...   0.00   
9   -2.91  4.08  0.00  0.00 -5.73  0.00  2.48 -5.29  0.00  1.46  ...   0.00   
10   1.31  1.80  2.57 -2.38  0.73  0.73 -0.97  5.00 -7.23 -1.36  ...   1.46   
11   0.00  0.00  0.00  0.00  5.87  0.00  5.58  0.53  0.00  7.14  ...   0.00   
12   9.22  9.27  9.22  8.30  7.43  0.44  3.50  8.16  5.97  8.98  ...   8.11   
13   8.79 -5.78  6.02  3.69  7.77 -5.83  8.69  8.59 -5.92  7.52  ...   2.72   
14  -3.50  1.55  2.33 -4.13  4.22 -2.28 -2.96 -0.49  2.91  1.99  ...   3.11   
15   0.00 -9.27  0.00  0.00 -7.38  0.00  8.74 -6.31  0.00  2.33  ...   0.00   
16   3.16  7.62  3.79  8.25  4.22  7.62  2.43  0.97  0.53  0.83  ...   0.83   
17   4.22  3.64  0.00  0.00  2.52  0.00  4.13 -5.19  0.00  7.91  ...   0.00   
18   0.00  7.62  0.00  0.00 -8.64  2.43  8.93 -6.60  0.00 -9.47  ...   0.00   
19   2.57 -0.73  0.00  0.00  2.57  0.00 -4.22  2.67  0.00 -1.31  ...   0.00   
20   7.28  5.39  0.00  0.00 -4.22  0.00  8.93  3.50  0.00  6.12  ...   0.00   
21   2.72  4.17  6.50 -3.54 -3.30  2.86  7.04  4.95  6.17  8.93  ...   0.00   
22   2.09 -7.57  4.17 -8.40 -6.31  5.34 -5.19 -5.05 -8.20  2.28  ...   3.06   
23  -3.93 -1.17  2.28 -0.44 -2.28  2.38 -3.93  4.51 -0.34  7.77  ...   0.00   
24   0.00  5.49  3.45  0.00  0.15  4.76  0.10  4.13  8.01  4.76  ...   0.00   
25   0.00  5.83  0.00  0.00  5.34  0.00 -4.47  2.18 -3.98 -3.25  ...   0.00   
26   0.49  0.15  0.15 -9.56 -9.76 -9.61  0.29  1.65 -4.61 -4.71  ...   0.00   
27   0.00  0.00  0.00  0.00 -1.70  0.00  8.83 -1.89  0.00  0.00  ...   0.24   
28   0.00  4.08  0.00  0.00  5.87  0.00  0.44  2.28  0.00  0.00  ...   0.00   
29   1.94  0.87  1.41  2.96  4.85  3.01  3.83 -4.27 -0.19  2.52  ...  -0.83   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
170 -4.56 -3.74 -2.67  0.00 -3.40  0.63 -5.34  0.44  5.34  4.08  ...   0.00   
171  0.00  0.00  0.00  0.00  4.37  0.00 -3.40  1.12  0.00  0.00  ...   0.00   
172  0.00  0.00  0.00  0.00  0.34  0.00 -1.65  0.83  0.00  0.00  ...   0.00   
173  0.00  0.00  0.00  0.00 -4.32  0.00  3.45  4.37  0.00  5.73  ...   0.00   
174 -9.42  8.83  8.45  8.64  5.73  8.45  6.89  4.56 -9.42 -9.22  ...   0.00   
175 -3.54 -3.20  1.12  3.83  3.30 -2.33 -0.19  2.33  0.05  1.17  ...   0.49   
176  5.39  0.24  0.00  0.00 -6.55  0.00 -8.35  3.40  0.00 -4.42  ...   0.00   
177  0.00  0.00  0.00  0.00  4.13  8.40  8.54  3.59  0.00  4.47  ...   0.00   
178  4.42 -5.05  0.00  0.00  1.55  0.00  6.60  2.18  0.00 -4.22  ...   0.00   
179  0.00  0.00  0.00  0.00  5.10  0.00 -6.31  1.21  0.00  0.00  ...   0.00   
180  5.44  0.49  0.00  0.00 -1.21  0.00  0.29 -0.63  0.00  5.53  ...   0.00   
181  0.00 -8.98 -9.66  0.00 -6.12 -7.91 -7.14 -5.24  0.00 -9.17  ...   0.00   
182  8.30  8.20  4.95  0.00  0.78  0.00  5.78 -2.77  0.00  0.00  ...   0.00   
183 -8.16 -7.86 -1.02  0.00  0.34  0.00  0.49 -0.29  0.00  2.14  ...   0.00   
184 -2.86 -6.31 -4.90  1.89  3.01  8.11  4.81  1.60 -4.95  9.03  ...   0.00   
185 -0.10 -5.68  1.50 -7.72 -7.91  1.12 -1.21 -3.74 -3.25 -1.89  ...   0.00   
186 -6.31 -1.94  0.00  0.00  3.69  0.00 -4.08  3.06  0.00  0.00  ...   0.00   
187  0.00  0.00  0.00  0.00  8.16  0.15  4.03  7.67  0.00  0.00  ...   0.00   
188  0.00 -3.16 -3.45  0.00  2.96 -1.65  1.75 -4.42  0.00

### Find user-user similarity and item-item similarity

**Hint:** Use **cosine_similarity()**

1. Get the user-user similarity by having users as rows. `(ratings matrix)`
2. Get the item-item similarity by having items as rows. `(ratings.T)` transpose.

### 1.Consine Similarity

In [39]:
cosine_users = linear_kernel(ratings_jokes, ratings_jokes)

In [40]:
cosine_users.shape

(200, 200)

In [41]:
cosine_item = linear_kernel(ratings_jokes.T, ratings_jokes.T)

In [42]:
cosine_item.shape

(100, 100)

### 2.Centered Cosine Similarity

Scale the ratings using StandardScaler

1. Pass the above data to StandardScaler().fit_transform() `consider it as ratings_diff` matrix

2. Use the above ratings_diff matrix to find 

    i. user-user similarity (cosine_similarity(ratings_diff))
    
    ii. item-item similarity (cosine_similarity(ratings_diff).T)

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
scaler = StandardScaler()
ratings_diff = scaler.fit_transform(ratings_jokes)

In [45]:
ratings_diff.shape

(200, 100)

In [46]:
cosine_users_scaled = linear_kernel(ratings_diff, ratings_diff)
cosine_users_scaled.shape

(200, 200)

In [47]:
cosine_items_scaled = linear_kernel(ratings_diff.T, ratings_diff.T)
cosine_items_scaled.shape

(100, 100)

#### Expected Output

In [48]:
ratings_diff

array([[ 0.78762067, -0.17252351,  1.37903679, ...,  0.07059963,
        -1.36765027,  0.16746078],
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       [-0.12768256,  1.60210964, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       ...,
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       [ 1.1241292 , -1.60825102, -1.1002121 , ..., -0.02685824,
        -0.04144395, -0.16095388],
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388]])

In [49]:
ratings_diff

array([[ 0.78762067, -0.17252351,  1.37903679, ...,  0.07059963,
        -1.36765027,  0.16746078],
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       [-0.12768256,  1.60210964, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       ...,
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388],
       [ 1.1241292 , -1.60825102, -1.1002121 , ..., -0.02685824,
        -0.04144395, -0.16095388],
       [-0.12768256, -0.11295828, -0.06492136, ..., -0.02685824,
        -0.04144395, -0.16095388]])

### Find the top 10 user ids similar to user 0

Similar to content based filtering, where we use argsort to get the indices based on values and get the last 10 indices from user_similarity matrix

`user_similarity[0].argsort()` gives the row of user 0.

get the last 10 values from the above list.

In [50]:
cosine_users_scaled[0].argsort()#[-1:-10:-1]

array([ 57, 122,   4, 174,   6, 140,  46,  62,  71,  42, 193,  52, 151,
        48,  90,  39,  55,   7, 114,  87,  60,  14, 141,  89, 196, 156,
        86,  70, 188, 123,  94, 139,  58,  26, 164, 109,  81, 181, 124,
        64,  25,  80,  47, 148,  10, 105, 189, 125,  63, 102,  83, 167,
        11,  23, 180, 198, 183, 106, 159,  29, 154, 190, 137, 192, 163,
       144, 145, 187, 185,  74, 175, 161, 171, 111, 115, 138, 160,  65,
        19,  36,  18,  50,  61,  84,  15,  27, 168, 178, 176,  40,   9,
       155,  79,  54,  22,  51,  38, 116, 143,  78,  97, 173,  56, 166,
       146, 179,  69,  76, 132, 142,  53, 197,  34,   2,  21, 135, 104,
        32, 101,  96, 184,  41,  99, 121,  98,  68, 133,  28, 186, 170,
        91, 150, 112, 128, 103,  95,  44, 118, 162, 100, 126, 177, 194,
       172,  73,  20, 130, 113,  17,   1,  30,   5, 182,  24, 165,  45,
       149,  67, 136,   3, 134,  92, 110, 147,  13, 129, 153, 127, 195,
       191, 199, 169,   8,  72,  66,  88, 107,  82,  35, 152, 11

In [51]:
cosine_users_scaled[0].argsort()

array([ 57, 122,   4, 174,   6, 140,  46,  62,  71,  42, 193,  52, 151,
        48,  90,  39,  55,   7, 114,  87,  60,  14, 141,  89, 196, 156,
        86,  70, 188, 123,  94, 139,  58,  26, 164, 109,  81, 181, 124,
        64,  25,  80,  47, 148,  10, 105, 189, 125,  63, 102,  83, 167,
        11,  23, 180, 198, 183, 106, 159,  29, 154, 190, 137, 192, 163,
       144, 145, 187, 185,  74, 175, 161, 171, 111, 115, 138, 160,  65,
        19,  36,  18,  50,  61,  84,  15,  27, 168, 178, 176,  40,   9,
       155,  79,  54,  22,  51,  38, 116, 143,  78,  97, 173,  56, 166,
       146, 179,  69,  76, 132, 142,  53, 197,  34,   2,  21, 135, 104,
        32, 101,  96, 184,  41,  99, 121,  98,  68, 133,  28, 186, 170,
        91, 150, 112, 128, 103,  95,  44, 118, 162, 100, 126, 177, 194,
       172,  73,  20, 130, 113,  17,   1,  30,   5, 182,  24, 165,  45,
       149,  67, 136,   3, 134,  92, 110, 147,  13, 129, 153, 127, 195,
       191, 199, 169,   8,  72,  66,  88, 107,  82,  35, 152, 11